//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project_SE_WebASPNET.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string PID { get; set; }
        public string PName { get; set; }
        public string PMemory { get; set; }
        public string PColor { get; set; }
        public Nullable<int> PQuantity { get; set; }
        public Nullable<int> PPrice { get; set; }
    }
}
